/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Command } from "./Command";
import { CommandCountArgs } from "./CommandCountArgs";
import { CommandFindManyArgs } from "./CommandFindManyArgs";
import { CommandFindUniqueArgs } from "./CommandFindUniqueArgs";
import { DeleteCommandArgs } from "./DeleteCommandArgs";
import { CommandService } from "../command.service";
@graphql.Resolver(() => Command)
export class CommandResolverBase {
  constructor(protected readonly service: CommandService) {}

  async _commandsMeta(
    @graphql.Args() args: CommandCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Command])
  async commands(
    @graphql.Args() args: CommandFindManyArgs
  ): Promise<Command[]> {
    return this.service.commands(args);
  }

  @graphql.Query(() => Command, { nullable: true })
  async command(
    @graphql.Args() args: CommandFindUniqueArgs
  ): Promise<Command | null> {
    const result = await this.service.command(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Command)
  async deleteCommand(
    @graphql.Args() args: DeleteCommandArgs
  ): Promise<Command | null> {
    try {
      return await this.service.deleteCommand(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
