/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResponseService } from "../response.service";
import { ResponseCreateInput } from "./ResponseCreateInput";
import { Response } from "./Response";
import { ResponseFindManyArgs } from "./ResponseFindManyArgs";
import { ResponseWhereUniqueInput } from "./ResponseWhereUniqueInput";
import { ResponseUpdateInput } from "./ResponseUpdateInput";

export class ResponseControllerBase {
  constructor(protected readonly service: ResponseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Response })
  async createResponse(
    @common.Body() data: ResponseCreateInput
  ): Promise<Response> {
    return await this.service.createResponse({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Response] })
  @ApiNestedQuery(ResponseFindManyArgs)
  async responses(@common.Req() request: Request): Promise<Response[]> {
    const args = plainToClass(ResponseFindManyArgs, request.query);
    return this.service.responses({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Response })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async response(
    @common.Param() params: ResponseWhereUniqueInput
  ): Promise<Response | null> {
    const result = await this.service.response({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Response })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResponse(
    @common.Param() params: ResponseWhereUniqueInput,
    @common.Body() data: ResponseUpdateInput
  ): Promise<Response | null> {
    try {
      return await this.service.updateResponse({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Response })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResponse(
    @common.Param() params: ResponseWhereUniqueInput
  ): Promise<Response | null> {
    try {
      return await this.service.deleteResponse({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
